### ISSUE TITLE
Matplotlib issue arise when importing tensorlayer

### ISSUE THREAD

**Issue by rylanchiu** [zsdonghao/tensorlayer#79]
I am working with conda environment. After installing `tensorlayer`, I tried to import it: `import tensorlayer as tl`, but got such an error:

	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorlayer/__init__.py", line 16, in <module>
	    from . import files
	  File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorlayer/files.py", line 13, in <module>
	    from . import visualize
	  File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorlayer/visualize.py", line 6, in <module>
	    import matplotlib.pyplot as plt
	  File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/matplotlib/pyplot.py", line 115, in <module>
	    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
	  File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
	    globals(),locals(),[backend_name],0)
	  File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
	    from .backend_qt5 import QtCore
	  File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 26, in <module>
	    import matplotlib.backends.qt_editor.figureoptions as figureoptions
	  File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
	    import matplotlib.backends.qt_editor.formlayout as formlayout
	  File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
	    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
	  File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 175, in <module>
	    "Matplotlib qt-based backends require an external PyQt4, PyQt5,\n"
	ImportError: Matplotlib qt-based backends require an external PyQt4, PyQt5,
	or PySide package to be installed, but it was not found.

This issue is not supposed to arise with conda. When I `import matplotlib` individually, it works well. I wonder how can I deal with this issue. Thanks in advance!

**Comment by wagamamaz** [comment]
can you try 
```
import matplotlib 
matplotlib.use('Agg')
import tensorlayer as tl
```

**Comment by rylanchiu** [comment]
It solved the problem perfectly! Thanks a lot!!!
